apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: icluster-kube-integration
  region: us-east-2

managedNodeGroups:
  - name: managed-ng-1
    instanceType: t2.2xlarge
    minSize: 2
    maxSize: 3
    desiredCapacity: 2
    availabilityZones: ["us-east-2a", "us-east-2b", "us-east-2c"]
    privateNetworking: true
