name: "$INSTALLNAME"
docker-flags:
  - log-driver awslogs
  - log-opt awslogs-group=tsuru-integration
  - log-opt tag={{.Name}}
  - experimental
docker-storage-driver: overlay
driver:
  name: amazonec2
  options:
    amazonec2-access-key: "$AWSKEY"
    amazonec2-secret-key: "$AWSSECRET"
    amazonec2-vpc-id: vpc-881598ed
    amazonec2-subnet-id: subnet-6d907c46
    amazonec2-instance-type: t2.xlarge
    amazonec2-iam-instance-profile: tsuru-integration-logs
hosts:
  apps:
    size: 0
    dedicated: true
components:
  install-dashboard: false
  tsuru:
    config:
      debug: true
      iaas:
        dockermachine:
          debug: true
