name: "$INSTALLNAME"
docker-flags:
  - log-driver awslogs
  - log-opt awslogs-group=tsuru-integration
  - log-opt tag={{.Name}}
  - experimental
docker-storage-driver: overlay
docker-install-url: https://raw.githubusercontent.com/rancher/install-docker/master/17.09.0.sh
driver:
  name: amazonec2
  options:
    amazonec2-access-key: "$AWSKEY"
    amazonec2-secret-key: "$AWSSECRET"
    amazonec2-vpc-id: "$AWS_VPC_ID"
    amazonec2-subnet-id: "$AWS_SUBNET_ID"
    amazonec2-instance-type: "$AWS_INSTANCE_TYPE"
    amazonec2-region: "$AWS_REGION"
    amazonec2-iam-instance-profile: tsuru-integration-logs
    amazonec2-security-group: docker-machine
hosts:
  apps:
    size: 0
    dedicated: true
components:
  install-dashboard: false
  tsuru-image: tsuru/api:$TSURUVERSION
  tsuru:
    config:
      debug: true
      iaas:
        dockermachine:
          debug: true
