version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.13
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install rsyslog xmlsec1 libsasl2-dev uuid-runtime
      - run:
          name: Run tests
          command: |
            while true; do echo .; sleep 30; done & ./run.sh